version: '3.8'

services:
  server:
    build: ./backend
    container_name: server_container
    ports:
      - "5000:5000"
    volumes: 
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb+srv://user:yZ5JyGomBfSWsP1e@cluster0.vt7rs.mongodb.net/auth_db
      - PORT=5000
      - JWT_SECRET=mysecretkey
      - NODE_ENV=development
      - MAILTRAP_TOKEN=97178a552df12850de6c6c36eb4344b9
      - MAILTRAP_ENDPOINT=https://send.api.mailtrap.io/
      - CLIENT_URL=http://localhost:5173

  client:
    build: ./frontend
    container_name: client_container
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
