name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build

      - name: Set up environment variables
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> backend/.env
          echo "PORT=${{ secrets.PORT }}" >> backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend/.env
          echo "MAILTRAP_TOKEN=${{ secrets.MAILTRAP_TOKEN }}" >> backend/.env
          echo "MAILTRAP_ENDPOINT=${{ secrets.MAILTRAP_ENDPOINT }}" >> backend/.env
          echo "CLIENT_URL=${{ secrets.CLIENT_URL }}" >> backend/.env

      - name: Restart application
        run: /home/ubuntu/.nvm/versions/node/v20.17.0/bin/pm2 start ecosystem.config.cjs
