name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # - name: Print environment variables
      # - run: |
      #     touch .env
      #     echo "MONGO_URI=${{ secrets.MONGO_URI }}"
      #     echo "PORT=${{ secrets.PORT }}"
      #     echo "JWT_SECRET=${{ secrets.JWT_SECRET }}"
      #     echo "MAILTRAP_TOKEN=${{ secrets.MAILTRAP_TOKEN }}"
      #     echo "MAILTRAP_ENDPOINT=${{ secrets.MAILTRAP_ENDPOINT }}"

      - run: npm ci
      - run: npm run build
      - run: npm ci
      - run: |
          touch .env
          echo "${{ secrets.MONGO_URI }}" > .env
          echo "${{ secrets.PORT }}" > .env
          echo "${{ secrets.JWT_SECRET }}" > .env
          echo "${{ secrets.MAILTRAP_TOKEN }}" > .env
          echo "${{ secrets.MAILTRAP_ENDPOINT }}" > .env

      - name: Restart application
        run: /home/ubuntu/.nvm/versions/node/v20.17.0/bin/pm2 restart app
